
package usuarios.vistas;

import interfaces.IControladorAMUsuario;
import java.awt.TextField;
import javax.swing.JComboBox;
import javax.swing.JPasswordField;
import usuarios.modelos.ModeloComboPerfiles;
import usuarios.modelos.Perfil;


public class VentanaAMUsuario extends javax.swing.JDialog {

    IControladorAMUsuario controlador;
    
    public VentanaAMUsuario(VentanaUsuarios ventanaPadre, IControladorAMUsuario controlador) {
        super(ventanaPadre, true);
        initComponents();
        this.controlador = controlador;
        
        ModeloComboPerfiles mcp = new ModeloComboPerfiles();
        this.comboPerfiles.setModel(mcp);
        Perfil p = Perfil.CLIENTE;
        ((ModeloComboPerfiles)this.comboPerfiles.getModel()).seleccionarPerfil(p);
        
    }

    public JComboBox<String> getComboPerfiles() {
        return comboPerfiles;
    }

    public void setComboPerfiles(JComboBox<String> comboPerfiles) {
        this.comboPerfiles = comboPerfiles;
    }

    public TextField getTxtApellido() {
        return txtApellido;
    }

    public void setTxtApellido(TextField txtApellido) {
        this.txtApellido = txtApellido;
    }

    public JPasswordField getClave() {
        return clave;
    }

    public void setClave(JPasswordField clave) {
        this.clave = clave;
    }

    public JPasswordField getClaveRepetida() {
        return claveRepetida;
    }

    public void setClaveRepetida(JPasswordField claveRepetida) {
        this.claveRepetida = claveRepetida;
    }   

    public TextField getTxtCorreo() {
        return txtCorreo;
    }

    public void setTxtCorreo(TextField txtCorreo) {
        this.txtCorreo = txtCorreo;
    }

    public TextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(TextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtClave = new java.awt.TextField();
        txtClaveRepetida = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        claveRepetida = new javax.swing.JPasswordField();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        comboPerfiles = new javax.swing.JComboBox<>();
        clave = new javax.swing.JPasswordField();
        txtNombre = new java.awt.TextField();
        txtApellido = new java.awt.TextField();
        txtCorreo = new java.awt.TextField();

        txtClave.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClic(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarClic(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        label1.setText("Correo:");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        label2.setText("Apellido:");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        label3.setText("Nombre:");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        label4.setText("Clave:");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        claveRepetida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveRepetida(evt);
            }
        });
        jPanel1.add(claveRepetida, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 274, -1));

        label5.setText("Repetir clave:");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 20));

        label6.setText("Perfil:");
        jPanel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        comboPerfiles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLIENTE", "EMPLEADO", "ENCARGADO" }));
        comboPerfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPerfiles(evt);
            }
        });
        jPanel1.add(comboPerfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 274, 20));
        comboPerfiles.getAccessibleContext().setAccessibleParent(comboPerfiles);

        clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clave(evt);
            }
        });
        jPanel1.add(clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 274, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 274, -1));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 274, -1));

        txtCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCorreo.setName("TextoCorreo"); // NOI18N
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 274, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 410, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void clave(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clave
        // TODO add your handling code here:
    }//GEN-LAST:event_clave

    private void comboPerfiles(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPerfiles
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPerfiles

    private void claveRepetida(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveRepetida
        // TODO add your handling code here:
    }//GEN-LAST:event_claveRepetida

    private void btnCancelarClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarClic
        controlador.btnCancelarClic(evt);
    }//GEN-LAST:event_btnCancelarClic

    private void btnGuardarClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClic
        controlador.btnGuardarClic(evt);
    }//GEN-LAST:event_btnGuardarClic


  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField clave;
    private javax.swing.JPasswordField claveRepetida;
    private javax.swing.JComboBox<String> comboPerfiles;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.TextField txtApellido;
    private java.awt.TextField txtClave;
    private java.awt.TextField txtClaveRepetida;
    private java.awt.TextField txtCorreo;
    private java.awt.TextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
